# Generated by Django 5.1.3 on 2024-11-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtbcourse',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mtbcourse',
            name='name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
