# Generated by Django 5.1.3 on 2024-11-29 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mtb_course', '0002_alter_mtbcourse_description_alter_mtbcourse_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mtbcourse',
            name='region',
            field=models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('강원', '강원'), ('충북', '충북'), ('충남', '충남'), ('전북', '전북'), ('전남', '전남'), ('경북', '경북'), ('경남', '경남'), ('제주', '제주')], default='서울', max_length=100),
        ),
        migrations.RemoveField(
            model_name='mtbcourse',
            name='create_at',
        ),
        migrations.AlterField(
            model_name='mtbcourse',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='mtbcourse',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.DeleteModel(
            name='Region',
        ),
    ]
